### ISSUE TITLE
Java 9/10 do not work

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/draft-guide-log4j#5]
We ran a build with some updated dependencies and with java versions 9/10, the build failed: https://travis-ci.org/OpenLiberty/draft-guide-log4j/builds/391965448?utm_source=github_status&utm_medium=notification

@evelinec @Ahmad-Ayyoub

**Comment by evelinec** [comment]
@Ahmad-Ayyoub and @proubatsis, one of you should try test (manually if needed) to make sure that this is a real issue, and try identify where is the problem. Pls add your finding here.

**Comment by proubatsis** [comment]
**Tested with:**

* Open JDK 9
* Oracle JDK 9
* Open JDK 10
* Oracle JDK 10

**Comment by evelinec** [comment]
@proubatsis all JDK had the same failure? What's the error message? Pls include OL build number tested and JDK versions.

**Comment by proubatsis** [comment]
**OL Build:** 18.0.0.1/wlp-1.0.20.cl180120180309-2209

**Comment by proubatsis** [comment]
The server starts, but there is some sort of error afterwards and the process does not terminate succesfully. One key difference between this guide and our other guides is that this one uses `liberty-maven-app-parent`.

![image](https://user-images.githubusercontent.com/8409464/41684768-7bc4abe0-74ac-11e8-8354-3c96e977f78b.png)

**Comment by proubatsis** [comment]
@evelinec @Ahmad-Ayyoub 

The is the error:

![image](https://user-images.githubusercontent.com/8409464/41724624-ec78d110-753b-11e8-9c3e-bb9853f55767.png)
https://travis-ci.org/OpenLiberty/draft-guide-log4j/jobs/395025573

---

I noticed that the error was due to a dependency in `jaxb-parent` so I tried upgrading jaxb to `2.3.0` since  `com:sun:tools:jar` is not listed in `2.3.0`. After this change, the server "started", but it also "failed" to start:
![image](https://user-images.githubusercontent.com/8409464/41724776-4a20d66e-753c-11e8-8b84-0490bea390b6.png)

https://travis-ci.org/OpenLiberty/draft-guide-log4j/jobs/395038389

This is from the `console.log` file:
```
Launching defaultServer (WebSphere Application Server 17.0.0.2/wlp-1.0.17.cl170220170523-1818) on Java HotSpot(TM) 64-Bit Server VM, version 10.0.1+10 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/17.0.0.2/lafiles/en.html
[ERROR   ] CWWKE0701E: FrameworkEvent ERROR Bundle:com.ibm.ws.config(id=8) org.osgi.framework.BundleException: Exception in com.ibm.ws.config.internal.WSConfigActivator.start() of bundle com.ibm.ws.config.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:795)
	at [internal classes]
Caused by: java.lang.NoClassDefFoundError: jdk/internal/reflect/SerializationConstructorAccessorImpl
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1192)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:112)
	at java.base/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:434)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:426)
	at java.base/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1516)
	at java.base/java.io.ObjectStreamClass.access$1500(ObjectStreamClass.java:81)
	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.base/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:484)
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:381)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1135)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at com.ibm.ws.config.admin.internal.ConfigurationStore.serializeConfigurationData(ConfigurationStore.java:213)
	... 1 more
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.SerializationConstructorAccessorImpl cannot be found by com.ibm.ws.config_1.0.17.cl170220170523-1818
	... 25 more
 Event:org.osgi.framework.FrameworkEvent[source=com.ibm.ws.config_1.0.17.cl170220170523-1818 [8]] 
```

**Comment by evelinec** [comment]
@proubatsis thank you for the investigation.

**Comment by evelinec** [comment]
@fwji can you take a look at how to fix this? We can't publish the guide without this fix. Thanks.

**Comment by fwji** [comment]
Sure, will take a look. Thanks for the extensive testing

**Comment by fwji** [comment]
I have committed the code for the jdk 10 build failure fix. How can I request a build to verify the fix?

**Comment by proubatsis** [comment]
I ran a build, it passed: https://travis-ci.org/OpenLiberty/draft-guide-log4j/builds/400872297
Thank you @fwji
